### ISSUE TITLE
Analysis Failure:  

### ISSUE THREAD

**Issue by gstafford** [racodond/sonar-css-plugin#117]
Trying to get my builds set up and ran into this problem on a scan of a scss file that is provided by my third party CMS.  This file is a scss file and it's failing with the below error.  I'm running version 3.0 of the CSS plugin and version 6.2 of SonarQube.

[_bootstrap-mixins.scss.txt](https://github.com/racodond/sonar-css-plugin/files/764829/_bootstrap-mixins.scss.txt)

`2017-02-09T19:07:04.9173838Z ##[error]ERROR: Error during SonarQube Scanner execution
2017-02-09T19:07:04.9173838Z ##[error]org.sonar.squidbridge.api.AnalysisException: Unable to analyze file: ...../ResourcePackages/Bootstrap/assets/src/sass/_bootstrap-mixins.scss
2017-02-09T19:07:04.9173838Z ##[error]at org.sonar.plugins.css.AbstractLanguageAnalyzerSensor.analyzeFile(AbstractLanguageAnalyzerSensor.java:148)
2017-02-09T19:07:04.9173838Z ##[error]at org.sonar.plugins.css.AbstractLanguageAnalyzerSensor.execute(AbstractLanguageAnalyzerSensor.java:111)
2017-02-09T19:07:04.9173838Z ##[error]at org.sonar.scanner.sensor.SensorWrapper.analyse(SensorWrapper.java:53)
2017-02-09T19:07:04.9173838Z ##[error]at org.sonar.scanner.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:57)
2017-02-09T19:07:04.9173838Z ##[error]at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:49)
2017-02-09T19:07:04.9173838Z ##[error]at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:78)
2017-02-09T19:07:04.9173838Z ##[error]at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:182)
2017-02-09T19:07:04.9173838Z ##[error]at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
2017-02-09T19:07:04.9173838Z ##[error]at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
2017-02-09T19:07:04.9173838Z ##[error]at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:247)
2017-02-09T19:07:04.9173838Z ##[error]at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:242)
2017-02-09T19:07:04.9173838Z ##[error]at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:240)
2017-02-09T19:07:04.9173838Z ##[error]at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:232)
2017-02-09T19:07:04.9173838Z ##[error]at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
2017-02-09T19:07:04.9173838Z ##[error]at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
2017-02-09T19:07:04.9173838Z ##[error]at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:47)
2017-02-09T19:07:04.9173838Z ##[error]at org.sonar.scanner.task.TaskContainer.doAfterStart(TaskContainer.java:86)
2017-02-09T19:07:04.9173838Z ##[error]at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
2017-02-09T19:07:04.9173838Z ##[error]at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
2017-02-09T19:07:04.9173838Z ##[error]at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:115)
2017-02-09T19:07:04.9173838Z ##[error]at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:116)
2017-02-09T19:07:04.9173838Z ##[error]at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:62)
2017-02-09T19:07:04.9330092Z ##[error]at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2017-02-09T19:07:04.9330092Z ##[error]at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
2017-02-09T19:07:04.9330092Z ##[error]at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
2017-02-09T19:07:04.9330092Z ##[error]at java.lang.reflect.Method.invoke(Unknown Source)
2017-02-09T19:07:04.9330092Z ##[error]at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
2017-02-09T19:07:04.9330092Z ##[error]at com.sun.proxy.$Proxy0.execute(Unknown Source)
2017-02-09T19:07:04.9330092Z ##[error]at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:233)
2017-02-09T19:07:04.9330092Z ##[error]at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScanner.java:151)
2017-02-09T19:07:04.9330092Z ##[error]at org.sonarsource.scanner.cli.Main.runAnalysis(Main.java:110)
2017-02-09T19:07:04.9330092Z ##[error]at org.sonarsource.scanner.cli.Main.execute(Main.java:74)
2017-02-09T19:07:04.9330092Z ##[error]at org.sonarsource.scanner.cli.Main.main(Main.java:61)
2017-02-09T19:07:04.9330092Z ##[error]Caused by: java.lang.NullPointerException
2017-02-09T19:07:04.9330092Z ##[error]at org.sonar.css.checks.common.BewareOfBoxModelCheck.visitNode(BewareOfBoxModelCheck.java:82)
2017-02-09T19:07:04.9330092Z ##[error]at org.sonar.plugins.css.api.visitors.SubscriptionVisitor.visit(SubscriptionVisitor.java:76)
2017-02-09T19:07:04.9330092Z ##[error]at org.sonar.plugins.css.api.visitors.SubscriptionVisitor.visitChildren(SubscriptionVisitor.java:96)
2017-02-09T19:07:04.9330092Z ##[error]at org.sonar.plugins.css.api.visitors.SubscriptionVisitor.visit(SubscriptionVisitor.java:78)
2017-02-09T19:07:04.9330092Z ##[error]at org.sonar.plugins.css.api.visitors.SubscriptionVisitor.visitChildren(SubscriptionVisitor.java:96)
2017-02-09T19:07:04.9330092Z ##[error]at org.sonar.plugins.css.api.visitors.SubscriptionVisitor.visit(SubscriptionVisitor.java:78)
2017-02-09T19:07:04.9330092Z ##[error]at org.sonar.plugins.css.api.visitors.SubscriptionVisitor.visitChildren(SubscriptionVisitor.java:96)
2017-02-09T19:07:04.9330092Z ##[error]at org.sonar.plugins.css.api.visitors.SubscriptionVisitor.visit(SubscriptionVisitor.java:78)
2017-02-09T19:07:04.9330092Z ##[error]at org.sonar.plugins.css.api.visitors.SubscriptionVisitor.scanTree(SubscriptionVisitor.java:70)
2017-02-09T19:07:04.9330092Z ##[error]at org.sonar.plugins.css.api.visitors.SubscriptionVisitor.scanTree(SubscriptionVisitor.java:64)
2017-02-09T19:07:04.9330092Z ##[error]at org.sonar.plugins.css.api.visitors.SubscriptionVisitorCheck.scanFile(SubscriptionVisitorCheck.java:40)
2017-02-09T19:07:04.9330092Z ##[error]at org.sonar.plugins.css.AbstractLanguageAnalyzerSensor.scanFile(AbstractLanguageAnalyzerSensor.java:161)
2017-02-09T19:07:04.9330092Z ##[error]at org.sonar.plugins.css.AbstractLanguageAnalyzerSensor.analyzeFile(AbstractLanguageAnalyzerSensor.java:138)
2017-02-09T19:07:04.9330092Z ##[error]... 32 more`

**Comment by racodond** [comment]
Hi @gstafford,

Thanks for your feedback!

This is a known issue (https://github.com/racodond/sonar-css-plugin/issues/115) that is fixed in version 3.1.

Version 3.1 is under feedback period: https://groups.google.com/forum/#!searchin/sonarqube/rff$20-$20css%7Csort:relevance/sonarqube/O1s5_v482cM/pDE8T0ZYAgAJ. Feel free to test the snapshot to confirm that it fixes your issue.

For your information, I expect to release version 3.1 by the end of the day if there's no blocker issue.

Cheers,

David
