### ISSUE TITLE
Error when parsing UTF-8 file with BOM

### ISSUE THREAD

**Issue by MartinDemberger** [racodond/sonar-css-plugin#39]
After the update to sonar-css-plugin 3.1 we get the error down below which breaks the full analysis of our projects. The error is gone if I remove the BOM-Header of the UTF-8 file.

I think such an error shouldn't break the hole analysis but only the one of this file. Also should the analyzer be able to run with a UTF-8 file with BOM.

org.sonar.squidbridge.api.AnalysisException: Unable to analyze file: C:/trunk/PGM/Orca.Ade.OfflineViewer/Client/offline/css/kunden_default.css
	at org.sonar.plugins.css.AbstractLanguageAnalyzerSensor.analyzeFile(AbstractLanguageAnalyzerSensor.java:148)
	at org.sonar.plugins.css.AbstractLanguageAnalyzerSensor.execute(AbstractLanguageAnalyzerSensor.java:111)
	at org.sonar.scanner.sensor.SensorWrapper.analyse(SensorWrapper.java:53)
	at org.sonar.scanner.phases.SensorsExecutor.executeSensor(SensorsExecutor.java:87)
	at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:81)
	at org.sonar.scanner.phases.SensorsExecutor.execute(SensorsExecutor.java:67)
	at org.sonar.scanner.phases.AbstractPhaseExecutor.execute(AbstractPhaseExecutor.java:75)
	at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:178)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:144)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:129)
	at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:259)
	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:254)
	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:252)
	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:243)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:144)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:129)
	at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:47)
	at org.sonar.scanner.task.TaskContainer.doAfterStart(TaskContainer.java:86)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:144)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:129)
	at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:118)
	at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:117)
	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
	at com.sun.proxy.$Proxy0.execute(Unknown Source)
	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:233)
	at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScanner.java:151)
	at org.sonarsource.scanner.cli.Main.runAnalysis(Main.java:123)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:77)
	at org.sonarsource.scanner.cli.Main.main(Main.java:61)
Caused by: java.lang.IllegalArgumentException: Unable to highlight file [moduleKey=ORCA:ORCA:9BCF20CC-E58F-43EF-8450-C4B49403E885, relative=Client/offline/css/kunden_default.css, basedir=C:\trunk\PGM\Orca.Ade.OfflineViewer]
	at org.sonar.api.batch.sensor.highlighting.internal.DefaultHighlighting.highlight(DefaultHighlighting.java:97)
	at org.sonar.api.batch.sensor.highlighting.internal.DefaultHighlighting.highlight(DefaultHighlighting.java:37)
	at org.sonar.css.visitors.highlighter.CssSyntaxHighlighterVisitor.highlight(CssSyntaxHighlighterVisitor.java:112)
	at org.sonar.css.visitors.highlighter.CssSyntaxHighlighterVisitor.highlightComments(CssSyntaxHighlighterVisitor.java:117)
	at org.sonar.css.visitors.highlighter.CssSyntaxHighlighterVisitor.visitNode(CssSyntaxHighlighterVisitor.java:103)
	at org.sonar.plugins.css.api.visitors.SubscriptionVisitor.visit(SubscriptionVisitor.java:76)
	at org.sonar.plugins.css.api.visitors.SubscriptionVisitor.visitChildren(SubscriptionVisitor.java:96)
	at org.sonar.plugins.css.api.visitors.SubscriptionVisitor.visit(SubscriptionVisitor.java:78)
	at org.sonar.plugins.css.api.visitors.SubscriptionVisitor.visitChildren(SubscriptionVisitor.java:96)
	at org.sonar.plugins.css.api.visitors.SubscriptionVisitor.visit(SubscriptionVisitor.java:78)
	at org.sonar.plugins.css.api.visitors.SubscriptionVisitor.visitChildren(SubscriptionVisitor.java:96)
	at org.sonar.plugins.css.api.visitors.SubscriptionVisitor.visit(SubscriptionVisitor.java:78)
	at org.sonar.plugins.css.api.visitors.SubscriptionVisitor.visitChildren(SubscriptionVisitor.java:96)
	at org.sonar.plugins.css.api.visitors.SubscriptionVisitor.visit(SubscriptionVisitor.java:78)
	at org.sonar.plugins.css.api.visitors.SubscriptionVisitor.visitChildren(SubscriptionVisitor.java:96)
	at org.sonar.plugins.css.api.visitors.SubscriptionVisitor.visit(SubscriptionVisitor.java:78)
	at org.sonar.plugins.css.api.visitors.SubscriptionVisitor.visitChildren(SubscriptionVisitor.java:96)
	at org.sonar.plugins.css.api.visitors.SubscriptionVisitor.visit(SubscriptionVisitor.java:78)
	at org.sonar.plugins.css.api.visitors.SubscriptionVisitor.scanTree(SubscriptionVisitor.java:70)
	at org.sonar.plugins.css.api.visitors.SubscriptionVisitor.scanTree(SubscriptionVisitor.java:64)
	at org.sonar.plugins.css.AbstractLanguageAnalyzerSensor.scanFile(AbstractLanguageAnalyzerSensor.java:163)
	at org.sonar.plugins.css.AbstractLanguageAnalyzerSensor.analyzeFile(AbstractLanguageAnalyzerSensor.java:138)
	... 33 more
Caused by: java.lang.IllegalArgumentException: 37 is not a valid line offset for pointer. File [moduleKey=ORCA:ORCA:9BCF20CC-E58F-43EF-8450-C4B49403E885, relative=Client/offline/css/kunden_default.css, basedir=C:\trunk\PGM\Orca.Ade.OfflineViewer] has 36 character(s) at line 1576
	at org.sonar.api.internal.google.common.base.Preconditions.checkArgument(Preconditions.java:145)
	at org.sonar.api.batch.fs.internal.DefaultInputFile.checkValid(DefaultInputFile.java:292)
	at org.sonar.api.batch.fs.internal.DefaultInputFile.newPointer(DefaultInputFile.java:226)
	at org.sonar.api.batch.fs.internal.DefaultInputFile.newRange(DefaultInputFile.java:242)
	at org.sonar.api.batch.sensor.highlighting.internal.DefaultHighlighting.highlight(DefaultHighlighting.java:95)
	... 54 more

**Comment by MartinDemberger** [comment]
Sorry, I don't see that the current version is 4.7. In Sonarqube the version 3.1 is shown as the current. But the error also occures in 4.7

**Comment by NikitaEgorov** [comment]
This bug reproduce on last version SonarQube (6.4) and last version extension 3.1

**Comment by NikitaEgorov** [comment]
```
2017-07-12T08:49:40.4097120Z ##[error]08:49:40.087 ERROR: Unable to parse file: C:/content/customized/webkit.less
2017-07-12T08:49:40.4116652Z ##[error]08:49:40.087 ERROR: Parse error at line 1 column 2:
2017-07-12T08:49:40.4116652Z ##[error]
2017-07-12T08:49:40.4116652Z ##[error]1: я╗┐.k-grid-column-resizing th, .k-grid-column-resizing td{
2017-07-12T08:49:40.4126418Z ##[error]^
2017-07-12T08:49:40.4136184Z ##[error]2:     -webkit-transform:none;
2017-07-12T08:49:40.4136184Z ##[error]3: }
2017-07-12T08:49:40.4145950Z ##[error]
```

**Comment by racodond** [comment]
@NikitaEgorov: Last version of the CSS plugin is 4.7 (not 3.1).

**Comment by racodond** [comment]
@MartinDemberger @NikitaEgorov I'm closing this ticket as it should work on version 4.7. If it doesn't, please open a new ticket and provide a file to reproduce. Thank you!

**Comment by NikitaEgorov** [comment]
@racodond 
In SonarQube update center last version is 3.1
```
CSS / SCSS / Less LanguagesEnables analysis of CSS and Less files | 3.1 installed | Homepage Issue TrackerLicensed under GNU LGPL 3Developed by Tamas Kende and David RACODON | Uninstall
-- | -- | -- | --

```

**Comment by racodond** [comment]
@NikitaEgorov See https://github.com/racodond/sonar-css-plugin/issues/24

**Comment by NikitaEgorov** [comment]
@racodond 

tnx!
